all:
	g++ -std=c++11 -o run_server server.cpp ../affine_cube/boundingvolume.cpp  ../affine_cube/bvtree.cpp  ../affine_cube/Vector.cpp -I../affine_cube/ -I../../../crow/include/ -lboost_system -L/home/nivan/Qt/5.4/gcc_64/lib -lpthread 
